Remove --insecure from curl command in entrypoint
Presumably no longer needed with the newer base image

$ docker run -v /media/crushingismybusiness/RAST_SDK_test/test_gtdb_tk_import/:/data gtdb_tk_test init
Traceback (most recent call last):
  File "./scripts/prepare_deploy_cfg.py", line 44, in <module>
    raise ValueError('Neither ' + sys.argv[2] + ' file nor KBASE_ENDPOINT env-variable found')
ValueError: Neither ./work/config.properties file nor KBASE_ENDPOINT env-variable found
Initialize module
Getting GTDB-Tk database
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 62.7G    0 5098k    0     0   162k      0   4d 16h  0:00:31   4d 16h  178k